### ISSUE TITLE
[feature] Replace the yellow/blue colour coding for server/client with silk icons

### ISSUE THREAD

**Issue by 100PXSquared** [100PXSquared/expression3.5#10]
**Describe the solution you'd like**
Having whether something needs to be run on server/client as a yellow/blue circle can be confusing if you don't already know which colour is which.  
I think they should be replaced by the following silk icons:
Server: server.png![](http://famfamfam.com/lab/icons/silk/icons/server.png)
Client: monitor.png![](http://famfamfam.com/lab/icons/silk/icons/monitor.png)
Server and client: computer_link.png![](http://famfamfam.com/lab/icons/silk/icons/computer_link.png)/accept.png![](http://famfamfam.com/lab/icons/silk/icons/accept.png) (personal preference is computer_link.png, could also use computer.png![](http://famfamfam.com/lab/icons/silk/icons/computer.png))

**Comment by x4fx77x4f** [comment]
Maybe, but the blue/yellow color scheme is already in use by [the StarfallEx documentation](https://thegrb93.github.io/StarfallEx/) and [the Garry's Mod wiki](https://wiki.facepunch.com/gmod/States). If you're worried about colorblind accessibility, the blue/yellow colors I used (coincidentally) happen to be easily distinguishable for most forms of colorblindness. If the icons get changed, the colors should still be retained in one form or another so as not to trip up anyone already familiar with them.

**Comment by 100PXSquared** [comment]
I could easily add an option to toggle graphic or colour depictions so if people aren't familiar with GMod's colour coding, they can just set them to the silk icons.

**Comment by 100PXSquared** [comment]
Added in commit de4286934233aa0afdf3d4eeb1221f35bbd83602
